<a href="https://colab.research.google.com/github/stac-bot/pandas/blob/master/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Loading data from kaggle

In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"ashutoshrudraksh","key":"180c7ef33a1ed44be18377bc640fdb29"}'}

In [ ]:
! mkdir ~/.kaggle

In [ ]:
! cp kaggle.json ~/.kaggle

In [ ]:
! chmod 600 ~/.kaggle/kaggle.json

In [ ]:
! kaggle datasets list

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /root/.kaggle/kaggle.json'
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.4)
ref                                                         title                                              size  lastUpdated          downloadCount
----------------------------------------------------------  ------------------------------------------------  -----  -------------------  -------------
gpreda/reddit-vaccine-myths                                 Reddit Vaccine Myths                              237KB  2021-12-12 11:59:54          18978
crowww/a-large-scale-fish-dataset                           A Large Scale Fish Dataset                          3GB  2021-04-28 17:03:01          11566
imsparsh/musicnet-dataset                                   MusicNet Dataset                                   22GB  2021-02-18 14:12:19           5945
dhruvildave/wikibooks-dataset                               Wikibooks Dataset                                   2GB  2021-10-22 10:48:21           4031
promptcloud/careerbuilder-job-listing-2020                  Careerbuilder Job Listing 2020                     42MB  2021-03-05 06:59:52           3115
mathurinache/twitter-edge-nodes                             Twitter Edge Nodes                                342MB  2021-03-08 06:43:04           1530
fatiimaezzahra/famous-iconic-women                          Famous Iconic Women                               838MB  2021-02-28 14:56:00           2191
mathurinache/the-lj-speech-dataset                          The LJ Speech Dataset                               3GB  2021-02-15 09:19:54            638
coloradokb/dandelionimages                                  DandelionImages                                     4GB  2021-02-19 20:03:47           1211
alsgroup/end-als                                            End ALS Kaggle Challenge                           12GB  2021-04-08 12:16:37           1253
simiotic/github-code-snippets                               GitHub Code Snippets                                7GB  2021-03-03 11:34:39            588
imsparsh/accentdb-core-extended                             AccentDB - Core & Extended                          6GB  2021-02-17 14:22:54            214
stuartjames/lights                                          LightS: Light Specularity Dataset                  18GB  2021-02-18 14:32:26            287
nickuzmenkov/ranzcr-clip-kfold-tfrecords                    RANZCR CLiP KFold TFRecords                         2GB  2021-02-21 13:29:51            178
landrykezebou/lvzhdr-tone-mapping-benchmark-dataset-tmonet  LVZ-HDR Tone Mapping Benchmark Dataset (TMO-Net)   24GB  2021-03-01 05:03:40            283
datasnaek/youtube-new                                       Trending YouTube Video Statistics                 201MB  2019-06-03 00:56:47         163812
zynicide/wine-reviews                                       Wine Reviews                                       51MB  2017-11-27 17:08:04         152848
residentmario/ramen-ratings                                 Ramen Ratings                                      40KB  2018-01-11 16:04:39          31962
datasnaek/chess                                             Chess Game Dataset (Lichess)                        3MB  2017-09-04 03:09:09          27105
rtatman/188-million-us-wildfires                            1.88 Million US Wildfires                         168MB  2020-05-12 21:03:49          18623

In [ ]:
!kaggle datasets download -d maca11/all-pokemon-dataset

Downloading all-pokemon-dataset.zip to /content
  0% 0.00/56.4k [00:00<?, ?B/s]
100% 56.4k/56.4k [00:00<00:00, 47.2MB/s]

In [ ]:
!unzip all-pokemon-dataset.zip

Archive:  all-pokemon-dataset.zip
  inflating: All_Pokemon.csv

Loading the pokemon dataset

In [ ]:
import pandas as pd

df = pd.read_csv(r'/content/All_Pokemon.csv')
#print(df.head(10))

df['HP'].head(20)

**Reading data in pandas**

In [ ]:
### 
##read columns
df.columns
##which gives you the list of the columns name

Index(['Number', 'Name', 'Type 1', 'Type 2', 'Abilities', 'HP', 'Att', 'Def',
       'Spa', 'Spd', 'Spe', 'BST', 'Mean', 'Standard Deviation', 'Generation',
       'Experience type', 'Experience to level 100', 'Final Evolution',
       'Catch Rate', 'Legendary', 'Mega Evolution', 'Alolan Form',
       'Galarian Form', 'Against Normal', 'Against Fire', 'Against Water',
       'Against Electric', 'Against Grass', 'Against Ice', 'Against Fighting',
       'Against Poison', 'Against Ground', 'Against Flying', 'Against Psychic',
       'Against Bug', 'Against Rock', 'Against Ghost', 'Against Dragon',
       'Against Dark', 'Against Steel', 'Against Fairy', 'Height', 'Weight',
       'BMI'],
      dtype='object')

In [ ]:
#read specific cloumn
print(df['Abilities'].head(10))
print(df[['Name','Att','Standard Deviation']].head(10))

0    ['Chlorophyll', 'Overgrow']
1    ['Chlorophyll', 'Overgrow']
2    ['Chlorophyll', 'Overgrow']
3                  ['Thick Fat']
4       ['Blaze', 'Solar Power']
5       ['Blaze', 'Solar Power']
6       ['Blaze', 'Solar Power']
7                    ['Drought']
8                ['Tough Claws']
9       ['Rain Dish', 'Torrent']
Name: Abilities, dtype: object
               Name  Att  Standard Deviation
0         Bulbasaur   49            8.640988
1           Ivysaur   62            8.902247
2          Venusaur   82            8.902247
3     Mega Venusaur  100           18.747592
4        Charmander   52            8.995369
5        Charmeleon   64            9.233093
6         Charizard   84           11.575837
7  Mega Charizard Y  104           27.378012
8  Mega Charizard X  130           20.154955
9          Squirtle   48            8.919392

In [ ]:
##printing each col name
for col in df.columns:
  print(col)

In [ ]:
##read each col
print(df.iloc[0:4])

   Number           Name Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
0       1      Bulbasaur  Grass  Poison  ...           0.5     0.7     6.9  14.1
1       2        Ivysaur  Grass  Poison  ...           0.5     1.0    13.0  13.0
2       3       Venusaur  Grass  Poison  ...           0.5     2.0   100.0  25.0
3       3  Mega Venusaur  Grass  Poison  ...           0.5     2.4   155.5  27.0

[4 rows x 44 columns]

In [ ]:
##by using the for loop 
for index, row in df.head(10).iterrows():
  print(index, row['Name'])

0 Bulbasaur
1 Ivysaur
2 Venusaur
3 Mega Venusaur
4 Charmander
5 Charmeleon
6 Charizard
7 Mega Charizard Y
8 Mega Charizard X
9 Squirtle

In [ ]:
df.head(10).loc[df['Type 1']=='Grass']

   Number           Name Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
0       1      Bulbasaur  Grass  Poison  ...           0.5     0.7     6.9  14.1
1       2        Ivysaur  Grass  Poison  ...           0.5     1.0    13.0  13.0
2       3       Venusaur  Grass  Poison  ...           0.5     2.0   100.0  25.0
3       3  Mega Venusaur  Grass  Poison  ...           0.5     2.4   155.5  27.0

[4 rows x 44 columns]

In [ ]:
##reading the specific row and columns
print(df.iloc[2,1])

Venusaur

**Sorting/Describing Data**

In [ ]:
df[['Name','HP']].sort_values(['Name','HP'], ascending=[0,1])

                     Name   HP
833      Zygarde Complete  216
832           Zygarde 10%   54
831               Zygarde  108
733              Zweilous   72
53                  Zubat   40
..                    ...  ...
788  Aegislash Blade Form   50
715              Accelgor   80
425                 Absol   65
80                   Abra   25
543             Abomasnow   90

[1032 rows x 2 columns]

In [ ]:
df.head(20)[['Name','Att','Def']].sort_values(['Att','Def'], ascending = [0,0])

                Name  Att  Def
19     Mega Beedrill  150   40
8   Mega Charizard X  130  111
7   Mega Charizard Y  104   78
12    Mega Blastoise  103  120
3      Mega Venusaur  100  123
18          Beedrill   90   40
6          Charizard   84   78
11         Blastoise   83  100
2           Venusaur   82   83
5         Charmeleon   64   58
10         Wartortle   63   80
1            Ivysaur   62   63
4         Charmander   52   43
0          Bulbasaur   49   49
9           Squirtle   48   65
15        Butterfree   45   50
16            Weedle   35   30
13          Caterpie   30   35
17            Kakuna   25   50
14           Metapod   20   55

**Making changes in data**

In [ ]:
#create new column 
df['Total'] = df['HP']+df['Att']+df['Def']
#df['Total']

df = df.drop(columns = ['Total'])#column deleted

cols = list(df.columns)
cols

['Number',
 'Name',
 'Type 1',
 'Type 2',
 'Abilities',
 'HP',
 'Att',
 'Def',
 'Spa',
 'Spd',
 'Spe',
 'BST',
 'Mean',
 'Standard Deviation',
 'Generation',
 'Experience type',
 'Experience to level 100',
 'Final Evolution',
 'Catch Rate',
 'Legendary',
 'Mega Evolution',
 'Alolan Form',
 'Galarian Form',
 'Against Normal',
 'Against Fire',
 'Against Water',
 'Against Electric',
 'Against Grass',
 'Against Ice',
 'Against Fighting',
 'Against Poison',
 'Against Ground',
 'Against Flying',
 'Against Psychic',
 'Against Bug',
 'Against Rock',
 'Against Ghost',
 'Against Dragon',
 'Against Dark',
 'Against Steel',
 'Against Fairy',
 'Height',
 'Weight',
 'BMI']

In [ ]:
df1 = df[cols[0:4] + [cols[-1]] + cols[4:12]]
df1

      Number                  Name   Type 1  Type 2  ...  Spa  Spd  Spe  BST
0          1             Bulbasaur    Grass  Poison  ...   65   65   45  318
1          2               Ivysaur    Grass  Poison  ...   80   80   60  405
2          3              Venusaur    Grass  Poison  ...  100  100   80  525
3          3         Mega Venusaur    Grass  Poison  ...  122  120   80  625
4          4            Charmander     Fire     NaN  ...   60   50   65  309
...      ...                   ...      ...     ...  ...  ...  ...  ...  ...
1027     896             Glastrier      Ice     NaN  ...   65  110   30  580
1028     897             Spectrier    Ghost     NaN  ...  145   80  130  580
1029     898               Calyrex  Psychic   Grass  ...   80   80   80  500
1030     898     Calyrex Ice Rider  Psychic     Ice  ...   85  130   50  680
1031     898  Calyrex Shadow Rider  Psychic   Ghost  ...  165  100  150  680

[1032 rows x 13 columns]

In [ ]:
80+82+83+100+100+80

525

**Saving our Data(Exporting into Desired Format)**

In [ ]:
df.to_csv('modified.csv', index = False)

df.to_excel("modified_to_excel.xlsx", sheet_name="passengers", index=False)

df.to_csv('modified2.txt', index = False, sep= '\t')

In [ ]:
df = pd.read_excel("modified_to_excel.xlsx", sheet_name="passengers")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1032 entries, 0 to 1031
Data columns (total 44 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Number                   1032 non-null   int64
 1   Name                     1032 non-null   object
 2   Type 1                   1032 non-null   object
 3   Type 2                   548 non-null    object
 4   Abilities                1032 non-null   object
 5   HP                       1032 non-null   int64
 6   Att                      1032 non-null   int64
 7   Def                      1032 non-null   int64
 8   Spa                      1032 non-null   int64
 9   Spd                      1032 non-null   int64
 10  Spe                      1032 non-null   int64
 11  BST                      1032 non-null   int64
 12  Mean                     1032 non-null   float64
 13  Standard Deviation       1032 non-null   float64
 14  Generation               1032 non-null   int64
 15  Experience type          1032 non-null   object
 16  Experience to level 100  1032 non-null   int64
 17  Final Evolution          1032 non-null   int64
 18  Catch Rate               1032 non-null   int64
 19  Legendary                1032 non-null   int64
 20  Mega Evolution           1032 non-null   int64
 21  Alolan Form              1032 non-null   int64
 22  Galarian Form            1032 non-null   int64
 23  Against Normal           1032 non-null   float64
 24  Against Fire             1032 non-null   float64
 25  Against Water            1032 non-null   float64
 26  Against Electric         1032 non-null   float64
 27  Against Grass            1032 non-null   float64
 28  Against Ice              1032 non-null   float64
 29  Against Fighting         1032 non-null   float64
 30  Against Poison           1032 non-null   float64
 31  Against Ground           1032 non-null   float64
 32  Against Flying           1032 non-null   float64
 33  Against Psychic          1032 non-null   float64
 34  Against Bug              1032 non-null   float64
 35  Against Rock             1032 non-null   float64
 36  Against Ghost            1032 non-null   float64
 37  Against Dragon           1032 non-null   float64
 38  Against Dark             1032 non-null   float64
 39  Against Steel            1032 non-null   float64
 40  Against Fairy            1032 non-null   float64
 41  Height                   1032 non-null   float64
 42  Weight                   1032 non-null   float64
 43  BMI                      1032 non-null   float64
dtypes: float64(23), int64(16), object(5)
memory usage: 354.9+ KB

**Filtering data**

In [ ]:
## filtering using the and as (&) ans or as (|)
new_df = df.loc[(df['Type 1']=='Grass') & (df['Type 2']=='Poison')]
new_df.reset_index(drop=True, inplace=True)
new_df.shape #using the shape to get the total number of rows and columns

new_df.to_csv('filtered.csv')

**conditional Changes**

In [ ]:
#type(df.columns)
#isinstance(df.columns)
#df.head(5)

In [ ]:
df.loc[df['Type 1']=='fire','Type 1']=True
df.head(23)
#df.loc[df['Total']>500, ['generation', Legendary]]==['Test 1','Test 2']

      Number                  Name   Type 1  ... Height Weight    BMI
1030     898     Calyrex Ice Rider  Psychic  ...    2.4  809.1  140.5
1031     898  Calyrex Shadow Rider  Psychic  ...    2.4   53.6    9.3

[2 rows x 44 columns]

In [ ]:




#df.loc[df['Att']>100, ['Generation','Legendary']] =['Test 1','Test 2']
#df
df = pd.read_csv('modified.csv')

**Aggregate Statistics(Groupby)**

In [ ]:
df = pd.read_csv('modified.csv')


df['count'] = 1
df.groupby(['Type 1','Type 2']).count()['count']

Type 1  Type 2
Bug     Electric     4
        Fairy        2
        Fighting     4
        Fire         2
        Flying      14
                    ..
Water   Ice          4
        Poison       3
        Psychic      6
        Rock         5
        Steel        1
Name: count, Length: 174, dtype: int64

handling exception

In [ ]:
import pandas as pd
import numpy as np


base = np.array([2,4,5,6])

try:
  base =='asdf'
except TypeError as e:
  print('TypeError:',str(e))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

**Working with large amount of data**

In [ ]:
new_df = pd.DataFrame(columns = df.columns)
new_df

Empty DataFrame
Columns: [Number, Name, Type 1, Type 2, Abilities, HP, Att, Def, Spa, Spd, Spe, BST, Mean, Standard Deviation, Generation, Experience type, Experience to level 100, Final Evolution, Catch Rate, Legendary, Mega Evolution, Alolan Form, Galarian Form, Against Normal, Against Fire, Against Water, Against Electric, Against Grass, Against Ice, Against Fighting, Against Poison, Against Ground, Against Flying, Against Psychic, Against Bug, Against Rock, Against Ghost, Against Dragon, Against Dark, Against Steel, Against Fairy, Height, Weight, BMI, count]
Index: []

In [ ]:
for df in pd.read_csv('modified.csv', chunksize=2):
  result = df.groupby(['Type 1']).count()

  new_df = pd.concat([new_df, result])

In [ ]:
new_df

        Number Name Type 1 Type 2  ... Height Weight BMI count
Grass        2    2    NaN      2  ...      2      2   2   NaN
Grass        2    2    NaN      2  ...      2      2   2   NaN
Fire         2    2    NaN      0  ...      2      2   2   NaN
Fire         2    2    NaN      2  ...      2      2   2   NaN
Fire         1    1    NaN      1  ...      1      1   1   NaN
...        ...  ...    ...    ...  ...    ...    ...  ..   ...
Dragon       1    1    NaN      0  ...      1      1   1   NaN
Ice          1    1    NaN      0  ...      1      1   1   NaN
Ghost        1    1    NaN      0  ...      1      1   1   NaN
Psychic      1    1    NaN      1  ...      1      1   1   NaN
Psychic      2    2    NaN      2  ...      2      2   2   NaN

[759 rows x 45 columns]

In [ ]:
df.groupby(['Type 1']).mean().sort_values('Att', ascending=True)

              Number         HP         Att  ...    Height      Weight          BMI
Type 1                                       ...
Fairy     541.772727  72.954545   68.090909  ...  0.927273   40.445455    19.263636
Bug       399.691358  57.024691   71.074074  ...  0.896296   33.954321    41.258025
Ghost     551.512195  62.731707   72.853659  ...  1.092683   49.592683    29.265854
Electric  469.440678  62.389831   74.169492  ...  0.979661   38.920339    33.332203
Grass     438.648352  66.736264   74.813187  ...  1.071429   39.839560    29.809890
Poison    328.075000  70.475000   74.900000  ...  1.730000   60.917500    30.187500
Water     374.450382  70.748092   74.923664  ...  1.454962   59.045038    33.547328
Flying    752.750000  69.625000   75.125000  ...  1.112500   41.225000    30.437500
Normal    382.719298  77.157895   75.263158  ...  1.021930   43.815789    34.882456
Psychic   460.207792  73.714286   76.909091  ...  1.389610   79.496104  1324.009091
Ice       456.263158  71.947368   78.526316  ...  1.239474  112.336842    52.889474
Dark      476.260870  70.065217   81.934783  ...  1.184783   58.034783    46.632609
Fire      402.718750  69.421875   85.640625  ...  1.218750   66.023438    40.814062
Rock      457.932203  67.474576   92.237288  ...  1.361017  116.266102    74.052542
Ground    408.170732  70.853659   94.121951  ...  1.358537  133.385366    53.843902
Steel     520.222222  68.972222   94.361111  ...  2.022222  231.113889    95.269444
Fighting  499.809524  72.928571  102.928571  ...  1.319048   78.411905    39.142857
Dragon    547.738095  86.785714  107.333333  ...  2.354762  139.559524    30.428571

[18 rows x 39 columns]

In [ ]:
#df.groupby(['Type 1']).sum()
#fill empty column having NAN

#new_df['count'].isna()
new_df['count'].fillna(1)

Grass      1
Grass      1
Fire       1
Fire       1
Fire       1
          ..
Dragon     1
Ice        1
Ghost      1
Psychic    1
Psychic    1
Name: count, Length: 759, dtype: int64

In [ ]:
#loading the data with chunksize
for df in pd.read_csv('modified.csv', chunksize=5):
  print("chunk si")
  print(df)
  #result = df.groupby(['Type 1']).count()

  #new_df = pd.concat([new_df,result])

chunk si
   Number           Name Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
0       1      Bulbasaur  Grass  Poison  ...           0.5     0.7     6.9  14.1
1       2        Ivysaur  Grass  Poison  ...           0.5     1.0    13.0  13.0
2       3       Venusaur  Grass  Poison  ...           0.5     2.0   100.0  25.0
3       3  Mega Venusaur  Grass  Poison  ...           0.5     2.4   155.5  27.0
4       4     Charmander   Fire     NaN  ...           0.5     0.6     8.5  23.6

[5 rows x 44 columns]
chunk si
   Number              Name Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
5       5        Charmeleon   Fire     NaN  ...           0.5     1.1    19.0  15.7
6       6         Charizard   Fire  Flying  ...           0.5     1.7    90.5  31.3
7       6  Mega Charizard Y   Fire  Flying  ...           0.5     1.7   100.5  34.8
8       6  Mega Charizard X   Fire  Dragon  ...           1.0     1.7   110.5  38.2
9       7          Squirtle  Water     NaN  ...           1.0     0.5     9.0  36.0

[5 rows x 44 columns]
chunk si
    Number            Name Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
10       8       Wartortle  Water     NaN  ...           1.0     1.0    22.5  22.5
11       9       Blastoise  Water     NaN  ...           1.0     1.6    85.5  33.4
12       9  Mega Blastoise  Water     NaN  ...           1.0     1.6   101.1  39.5
13      10        Caterpie    Bug     NaN  ...           1.0     0.3     2.9  32.2
14      11         Metapod    Bug     NaN  ...           1.0     0.7     9.9  20.2

[5 rows x 44 columns]
chunk si
    Number           Name Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
15      12     Butterfree    Bug  Flying  ...           1.0     1.1    32.0  26.4
16      13         Weedle    Bug  Poison  ...           0.5     0.3     3.2  35.6
17      14         Kakuna    Bug  Poison  ...           0.5     0.6    10.0  27.8
18      15       Beedrill    Bug  Poison  ...           0.5     1.0    29.5  29.5
19      15  Mega Beedrill    Bug  Poison  ...           0.5     1.4    40.5  20.7

[5 rows x 44 columns]
chunk si
    Number          Name  Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
20      16        Pidgey  Normal  Flying  ...           1.0     0.3     1.8  20.0
21      17     Pidgeotto  Normal  Flying  ...           1.0     1.1    30.0  24.8
22      18       Pidgeot  Normal  Flying  ...           1.0     1.5    39.5  17.6
23      18  Mega Pidgeot  Normal  Flying  ...           1.0     2.2    50.5  10.4
24      19       Rattata  Normal     NaN  ...           1.0     0.3     3.5  38.9

[5 rows x 44 columns]
chunk si
    Number             Name  Type 1  ... Height Weight   BMI
25      19   Alolan Rattata    Dark  ...    0.3    3.8  42.2
26      20         Raticate  Normal  ...    0.7   18.5  37.8
27      20  Alolan Raticate    Dark  ...    0.7   25.5  52.0
28      21          Spearow  Normal  ...    0.3    2.0  22.2
29      22           Fearow  Normal  ...    1.2   38.0  26.4

[5 rows x 44 columns]
chunk si
    Number           Name    Type 1  ... Height Weight   BMI
30      23          Ekans    Poison  ...    2.0    6.9   1.7
31      24          Arbok    Poison  ...    3.5   65.0   5.3
32      25        Pikachu  Electric  ...    0.4    6.0  37.5
33      26         Raichu  Electric  ...    0.8   30.0  46.9
34      26  Alolan Raichu  Electric  ...    0.7   21.0  42.9

[5 rows x 44 columns]
chunk si
    Number              Name  Type 1  ... Height Weight   BMI
35      27         Sandshrew  Ground  ...    0.6   12.0  33.3
36      27  Alolan Sandshrew     Ice  ...    0.7   40.0  81.6
37      28         Sandslash  Ground  ...    1.0   29.5  29.5
38      28  Alolan Sandslash     Ice  ...    1.2   55.0  38.2
39      29          Nidoran♀  Poison  ...    0.4    7.0  43.8

[5 rows x 44 columns]
chunk si
    Number       Name  Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
40      30   Nidorina  Poison     NaN  ...           0.5     0.8    20.0  31.3
41      31  Nidoqueen  Poison  Ground  ...           0.5     1.3    60.0  35.5
42      32   Nidoran♂  Poison     NaN  ...           0.5     0.5     9.0  36.0
43      33   Nidorino  Poison     NaN  ...           0.5     0.9    19.5  24.1
44      34   Nidoking  Poison  Ground  ...           0.5     1.4    62.0  31.6

[5 rows x 44 columns]
chunk si
    Number           Name Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
45      35       Clefairy  Fairy     NaN  ...           1.0     0.6     7.5  20.8
46      36       Clefable  Fairy     NaN  ...           1.0     1.3    40.0  23.7
47      37         Vulpix   Fire     NaN  ...           0.5     0.6     9.9  27.5
48      37  Alolan Vulpix    Ice     NaN  ...           1.0     0.6     9.9  27.5
49      38      Ninetales   Fire     NaN  ...           0.5     1.1    19.9  16.4

[5 rows x 44 columns]
chunk si
    Number              Name  Type 1  ... Height Weight   BMI
50      38  Alolan Ninetales     Ice  ...    1.1   19.9  16.4
51      39        Jigglypuff  Normal  ...    0.5    5.5  22.0
52      40        Wigglytuff  Normal  ...    1.0   12.0  12.0
53      41             Zubat  Poison  ...    0.8    7.5  11.7
54      42            Golbat  Poison  ...    1.6   55.0  21.5

[5 rows x 44 columns]
chunk si
    Number       Name Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
55      43     Oddish  Grass  Poison  ...           0.5     0.5     5.4  21.6
56      44      Gloom  Grass  Poison  ...           0.5     0.8     8.6  13.4
57      45  Vileplume  Grass  Poison  ...           0.5     1.2    18.6  12.9
58      46      Paras    Bug   Grass  ...           1.0     0.3     5.4  60.0
59      47   Parasect    Bug   Grass  ...           1.0     1.0    29.5  29.5

[5 rows x 44 columns]
chunk si
    Number            Name  Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
60      48         Venonat     Bug  Poison  ...           0.5     1.0    30.0  30.0
61      49        Venomoth     Bug  Poison  ...           0.5     1.5    12.5   5.6
62      50         Diglett  Ground     NaN  ...           1.0     0.2     0.8  20.0
63      50  Alolan Diglett  Ground   Steel  ...           0.5     0.2     1.0  25.0
64      51         Dugtrio  Ground     NaN  ...           1.0     0.7    33.3  68.0

[5 rows x 44 columns]
chunk si
    Number             Name  Type 1  ... Height Weight    BMI
65      51   Alolan Dugtrio  Ground  ...    0.7   66.6  135.9
66      52           Meowth  Normal  ...    0.4    4.2   26.3
67      52    Alolan Meowth    Dark  ...    0.4    4.2   26.3
68      52  Galarian Meowth   Steel  ...    0.4    7.5   46.9
69      53          Persian  Normal  ...    1.0   32.0   32.0

[5 rows x 44 columns]
chunk si
    Number            Name    Type 1  ...  Height Weight    BMI
70      53  Alolan Persian      Dark  ...     1.1   33.0   27.3
71      54         Psyduck     Water  ...     0.8   19.6   30.6
72      55         Golduck     Water  ...     1.7   76.6   26.5
73      56          Mankey  Fighting  ...     0.5   28.0  112.0
74      57        Primeape  Fighting  ...     1.0   32.0   32.0

[5 rows x 44 columns]
chunk si
    Number       Name Type 1    Type 2  ... Against Fairy  Height  Weight   BMI
75      58  Growlithe   Fire       NaN  ...           0.5     0.7    19.0  38.8
76      59   Arcanine   Fire       NaN  ...           0.5     1.9   155.0  42.9
77      60    Poliwag  Water       NaN  ...           1.0     0.6    12.4  34.4
78      61  Poliwhirl  Water       NaN  ...           1.0     1.0    20.0  20.0
79      62  Poliwrath  Water  Fighting  ...           2.0     1.3    54.0  32.0

[5 rows x 44 columns]
chunk si
    Number           Name    Type 1  ...  Height Weight   BMI
80      63           Abra   Psychic  ...     0.9   19.5  24.1
81      64        Kadabra   Psychic  ...     1.3   56.5  33.4
82      65       Alakazam   Psychic  ...     1.5   48.0  21.3
83      65  Mega Alakazam   Psychic  ...     1.2   48.0  33.3
84      66         Machop  Fighting  ...     0.8   19.5  30.5

[5 rows x 44 columns]
chunk si
    Number        Name    Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
85      67     Machoke  Fighting     NaN  ...           2.0     1.5    70.5  31.3
86      68     Machamp  Fighting     NaN  ...           2.0     1.6   130.0  50.8
87      69  Bellsprout     Grass  Poison  ...           0.5     0.7     4.0   8.2
88      70  Weepinbell     Grass  Poison  ...           0.5     1.0     6.4   6.4
89      71  Victreebel     Grass  Poison  ...           0.5     1.7    15.5   5.4

[5 rows x 44 columns]
chunk si
    Number            Name Type 1  ... Height Weight    BMI
90      72       Tentacool  Water  ...    0.9   45.5   56.2
91      73      Tentacruel  Water  ...    1.6   55.0   21.5
92      74         Geodude   Rock  ...    0.4   20.0  125.0
93      74  Alolan Geodude   Rock  ...    0.4   20.3  126.9
94      75        Graveler   Rock  ...    1.0  105.0  105.0

[5 rows x 44 columns]
chunk si
    Number             Name   Type 1  ... Height Weight    BMI
95      75  Alolan Graveler     Rock  ...    1.0  110.0  110.0
96      76            Golem     Rock  ...    1.4  300.0  153.1
97      76     Alolan Golem     Rock  ...    1.7  316.0  109.3
98      77           Ponyta     Fire  ...    1.0   30.0   30.0
99      77  Galarian Ponyta  Psychic  ...    0.8   24.0   37.5

[5 rows x 44 columns]
chunk si
     Number               Name   Type 1  ... Height Weight   BMI
100      78           Rapidash     Fire  ...    1.7   95.0  32.9
101      78  Galarian Rapidash  Psychic  ...    1.7   80.0  27.7
102      79           Slowpoke    Water  ...    1.2   36.0  25.0
103      79  Galarian Slowpoke  Psychic  ...    1.2   36.0  25.0
104      80            Slowbro    Water  ...    1.6   78.5  30.7

[5 rows x 44 columns]
chunk si
     Number              Name    Type 1  ... Height Weight   BMI
105      80      Mega Slowbro     Water  ...    2.0  120.0  30.0
106      80  Galarian Slowbro    Poison  ...    1.6   70.5  27.5
107      81         Magnemite  Electric  ...    0.3    6.0  66.7
108      82          Magneton  Electric  ...    1.0   60.0  60.0
109      83        Farfetch'd    Normal  ...    0.8   15.0  23.4

[5 rows x 44 columns]
chunk si
     Number                 Name    Type 1  ... Height Weight   BMI
110      83  Galarian Farfetch'd  Fighting  ...    0.8   42.0  65.6
111      84                Doduo    Normal  ...    1.4   39.2  20.0
112      85               Dodrio    Normal  ...    1.8   85.2  26.3
113      86                 Seel     Water  ...    1.1   90.0  74.4
114      87              Dewgong     Water  ...    1.7  120.0  41.5

[5 rows x 44 columns]
chunk si
     Number           Name  Type 1 Type 2  ... Against Fairy  Height  Weight   BMI
115      88         Grimer  Poison    NaN  ...           0.5     0.9    30.0  37.0
116      88  Alolan Grimer  Poison   Dark  ...           1.0     0.7    42.0  85.7
117      89            Muk  Poison    NaN  ...           0.5     1.2    30.0  20.8
118      89     Alolan Muk  Poison   Dark  ...           1.0     1.0    52.0  52.0
119      90       Shellder   Water    NaN  ...           1.0     0.3     4.0  44.4

[5 rows x 44 columns]
chunk si
     Number         Name Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
120      91     Cloyster  Water     Ice  ...           1.0     1.5   132.5  58.9
121      92       Gastly  Ghost  Poison  ...           0.5     1.3     0.1   0.1
122      93      Haunter  Ghost  Poison  ...           0.5     1.6     0.1   0.0
123      94       Gengar  Ghost  Poison  ...           0.5     1.5    40.5  18.0
124      94  Mega Gengar  Ghost  Poison  ...           0.5     1.4    40.5  20.7

[5 rows x 44 columns]
chunk si
     Number     Name   Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
125      95     Onix     Rock  Ground  ...           1.0     8.8   210.0   2.7
126      96  Drowzee  Psychic     NaN  ...           1.0     1.0    32.4  32.4
127      97    Hypno  Psychic     NaN  ...           1.0     1.6    75.6  29.5
128      98   Krabby    Water     NaN  ...           1.0     0.4     6.5  40.6
129      99  Kingler    Water     NaN  ...           1.0     1.3    60.0  35.5

[5 rows x 44 columns]
chunk si
     Number              Name    Type 1  ... Height Weight   BMI
130     100           Voltorb  Electric  ...    0.5   10.4  41.6
131     101         Electrode  Electric  ...    1.2   66.6  46.3
132     102         Exeggcute     Grass  ...    0.4    2.5  15.6
133     103         Exeggutor     Grass  ...    2.0  120.0  30.0
134     103  Alolan Exeggutor     Grass  ...   10.9  415.6   3.5

[5 rows x 44 columns]
chunk si
     Number            Name    Type 1  ... Height Weight   BMI
135     104          Cubone    Ground  ...    0.4    6.5  40.6
136     105         Marowak    Ground  ...    1.0   45.0  45.0
137     105  Alolan Marowak      Fire  ...    1.0   34.0  34.0
138     106       Hitmonlee  Fighting  ...    1.5   49.8  22.1
139     107      Hitmonchan  Fighting  ...    1.4   50.2  25.6

[5 rows x 44 columns]
chunk si
     Number              Name  Type 1  ... Height Weight    BMI
140     108         Lickitung  Normal  ...    1.2   65.5   45.5
141     109           Koffing  Poison  ...    0.6    1.0    2.8
142     110           Weezing  Poison  ...    1.2    9.5    6.6
143     110  Galarian Weezing  Poison  ...    3.0   16.0    1.8
144     111           Rhyhorn  Ground  ...    1.0  115.0  115.0

[5 rows x 44 columns]
chunk si
     Number             Name  Type 1  ... Height Weight   BMI
145     112           Rhydon  Ground  ...    1.9  120.0  33.2
146     113          Chansey  Normal  ...    1.1   34.6  28.6
147     114          Tangela   Grass  ...    1.0   35.0  35.0
148     115       Kangaskhan  Normal  ...    2.2   80.0  16.5
149     115  Mega Kangaskhan  Normal  ...    2.2  100.0  20.7

[5 rows x 44 columns]
chunk si
     Number     Name Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
150     116   Horsea  Water     NaN  ...           1.0     0.4     8.0  50.0
151     117   Seadra  Water     NaN  ...           1.0     1.2    25.0  17.4
152     118  Goldeen  Water     NaN  ...           1.0     0.6    15.0  41.7
153     119  Seaking  Water     NaN  ...           1.0     1.3    39.0  23.1
154     120   Staryu  Water     NaN  ...           1.0     0.8    34.5  53.9

[5 rows x 44 columns]
chunk si
     Number               Name   Type 1  ... Height Weight   BMI
155     121            Starmie    Water  ...    1.1   80.0  66.1
156     122           Mr. Mime  Psychic  ...    1.3   54.5  32.2
157     122  Galarian Mr. Mime      Ice  ...    1.4   56.8  29.0
158     123            Scyther      Bug  ...    1.5   56.0  24.9
159     124               Jynx      Ice  ...    1.4   40.6  20.7

[5 rows x 44 columns]
chunk si
     Number         Name    Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
160     125   Electabuzz  Electric     NaN  ...           1.0     1.1    30.0  24.8
161     126       Magmar      Fire     NaN  ...           0.5     1.3    44.5  26.3
162     127       Pinsir       Bug     NaN  ...           1.0     1.5    55.0  24.4
163     127  Mega Pinsir       Bug  Flying  ...           1.0     1.7    59.0  20.4
164     128       Tauros    Normal     NaN  ...           1.0     1.4    88.4  45.1

[5 rows x 44 columns]
chunk si
     Number           Name  Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
165     129       Magikarp   Water     NaN  ...           1.0     0.9    10.0  12.3
166     130       Gyarados   Water  Flying  ...           1.0     6.5   235.0   5.6
167     130  Mega Gyarados   Water    Dark  ...           2.0     6.5   305.0   7.2
168     131         Lapras   Water     Ice  ...           1.0     2.5   220.0  35.2
169     132          Ditto  Normal     NaN  ...           1.0     0.3     4.0  44.4

[5 rows x 44 columns]
chunk si
     Number      Name    Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
170     133     Eevee    Normal     NaN  ...           1.0     0.3     6.5  72.2
171     134  Vaporeon     Water     NaN  ...           1.0     1.0    29.0  29.0
172     135   Jolteon  Electric     NaN  ...           1.0     0.8    24.5  38.3
173     136   Flareon      Fire     NaN  ...           0.5     0.9    25.0  30.9
174     137   Porygon    Normal     NaN  ...           1.0     0.8    36.5  57.0

[5 rows x 44 columns]
chunk si
     Number        Name Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
175     138     Omanyte   Rock   Water  ...           1.0     0.4     7.5  46.9
176     139     Omastar   Rock   Water  ...           1.0     1.0    35.0  35.0
177     140      Kabuto   Rock   Water  ...           1.0     0.5    11.5  46.0
178     141    Kabutops   Rock   Water  ...           1.0     1.3    40.5  24.0
179     142  Aerodactyl   Rock  Flying  ...           1.0     1.8    59.0  18.2

[5 rows x 44 columns]
chunk si
     Number               Name    Type 1  ... Height Weight    BMI
180     142    Mega Aerodactyl      Rock  ...    2.1   79.0   17.9
181     143            Snorlax    Normal  ...    2.1  460.0  104.3
182     144           Articuno       Ice  ...    1.7   55.4   19.2
183     144  Galarian Articuno   Psychic  ...    1.7   50.9   17.6
184     145             Zapdos  Electric  ...    1.6   52.6   20.5

[5 rows x 44 columns]
chunk si
     Number              Name    Type 1  ... Height Weight   BMI
185     145   Galarian Zapdos  Fighting  ...    1.6   58.2  22.7
186     146           Moltres      Fire  ...    2.0   60.0  15.0
187     146  Galarian Moltres      Dark  ...    2.0   66.0  16.5
188     147           Dratini    Dragon  ...    1.8    3.3   1.0
189     148         Dragonair    Dragon  ...    4.0   16.5   1.0

[5 rows x 44 columns]
chunk si
     Number           Name   Type 1  ... Height Weight   BMI
190     149      Dragonite   Dragon  ...    2.2  210.0  43.4
191     150         Mewtwo  Psychic  ...    2.0  122.0  30.5
192     150  Mega Mewtwo Y  Psychic  ...    1.5   33.0  14.7
193     150  Mega Mewtwo X  Psychic  ...    2.3  127.0  24.0
194     151            Mew  Psychic  ...    0.4    4.0  25.0

[5 rows x 44 columns]
chunk si
     Number       Name Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
195     152  Chikorita  Grass     NaN  ...           1.0     0.9     6.4   7.9
196     153    Bayleef  Grass     NaN  ...           1.0     1.2    15.8  11.0
197     154   Meganium  Grass     NaN  ...           1.0     1.8   100.5  31.0
198     155  Cyndaquil   Fire     NaN  ...           0.5     0.5     7.9  31.6
199     156    Quilava   Fire     NaN  ...           0.5     0.9    19.0  23.5

[5 rows x 44 columns]
chunk si
     Number        Name  Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
200     157  Typhlosion    Fire     NaN  ...           0.5     1.7    79.5  27.5
201     158    Totodile   Water     NaN  ...           1.0     0.6     9.5  26.4
202     159    Croconaw   Water     NaN  ...           1.0     1.1    25.0  20.7
203     160  Feraligatr   Water     NaN  ...           1.0     2.3    88.8  16.8
204     161     Sentret  Normal     NaN  ...           1.0     0.8     6.0   9.4

[5 rows x 44 columns]
chunk si
     Number      Name  Type 1  Type 2  ... Against Fairy  Height  Weight   BMI
205     162    Furret  Normal     NaN  ...           1.0     1.8    32.5  10.0
206     163  Hoothoot  Normal  Flying  ...           1.0     0.7    21.2  43.3
207     164   Noctowl  Normal  Flying  ...           1.0     1.6    40.8  15.9
208     165    Ledyba     Bug  Flying  ...           1.0     1.0    10.8  10.8
209     166    Ledian     Bug  Flying  ...           1.0     1.4    35.6  18.2

[5 rows x 44 columns]
chunk si
     Number      Name  Type 1    Type 2  ... Against Fairy  Height  Weight   BMI
210     167  Spinarak     Bug    Poison  ...           0.5     0.5     8.5  34.0
211     168   Ariados     Bug    Poison  ...           0.5     1.1    33.5  27.7
212     169    Crobat  Poison    Flying  ...           0.5     1.8    75.0  23.1